### ISSUE TITLE
Method dirichlet_dofs in API

### ISSUE THREAD

**Issue by keileg** [TheBB/Costa#2]
@TheBB The method `dirichlet_dofs()` in the API is presumably aimed at finite element discretizations. For a cell centered finite volume discretization, where boundary conditions are discretized differently (in a certain sense) from interior dofs,  it is not meaningful to ask for Dirichlet dofs. In such cases, should the method simply return an empty list?

**Comment by TheBB** [comment]
Yes, the idea is to distinguish fixed dofs, so for finite volumes presumably no dofs are fixed (and, correspondingly, all entries in the load vector are of significance), so the return value should be `[]`.

**Comment by keileg** [comment]
Thanks.
